2020-05-07 00:27:59.422 +03:00 [Error] Failed executing DbCommand ("6"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""CREATE TABLE [Dockets] (
    [Id] nvarchar(450) NOT NULL,
    [Name] nvarchar(max) NULL,
    [Instance] nvarchar(max) NULL,
    CONSTRAINT [PK_Dockets] PRIMARY KEY ([Id])
);"
System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'Dockets' in the database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:af13a085-6283-4bf2-a374-b8b89e35914e
Error Number:2714,State:6,Class:16
2020-05-07 00:34:26.852 +03:00 [Error] Failed executing DbCommand ("7"ms) [Parameters=["@p0='?' (DbType = Guid), @p1='?' (DbType = DateTime2), @p2='?' (DbType = DateTime2), @p3='?' (DbType = Guid), @p4='?' (DbType = Int32), @p5='?' (Size = 4000), @p6='?' (DbType = Int32), @p7='?' (DbType = Int32), @p8='?' (DbType = Int32), @p9='?' (DbType = Int32), @p10='?' (DbType = DateTime2)"], CommandType='Text', CommandTimeout='30']"
""SET NOCOUNT ON;
INSERT INTO [Manifests] ([Id], [DateArrived], [DateLogged], [FacilityId], [ManifestType], [Name], [Recieved], [Sent], [SiteCode], [Status], [StatusDate])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10);"
System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ManifestType'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
ClientConnectionId:af13a085-6283-4bf2-a374-b8b89e35914e
Error Number:207,State:1,Class:16
2020-05-07 00:34:26.863 +03:00 [Error] An exception occurred in the database while saving changes for context type '"DwapiCentral.Cbs.Infrastructure.Data.CbsContext"'."
""Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Invalid column name 'ManifestType'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)"
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Invalid column name 'ManifestType'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
2020-05-07 00:34:26.894 +03:00 [Error] manifest error
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Invalid column name 'ManifestType'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at DwapiCentral.Cbs.Core.CommandHandler.SaveManifestHandler.Handle(SaveManifest request, CancellationToken cancellationToken) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral.Cbs.Core/CommandHandler/SaveManifestHandler.cs:line 27
   at DwapiCentral.Controllers.CbsController.ProcessManifest(SaveManifest manifest) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral/Controllers/CbsController.cs:line 60
2020-05-07 00:37:53.789 +03:00 [Error] Failed executing DbCommand ("5"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""CREATE TABLE [Dockets] (
    [Id] nvarchar(450) NOT NULL,
    [Name] nvarchar(max) NULL,
    [Instance] nvarchar(max) NULL,
    CONSTRAINT [PK_Dockets] PRIMARY KEY ([Id])
);"
System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'Dockets' in the database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:1610dc92-942a-4e0f-8039-f500a7f867d5
Error Number:2714,State:6,Class:16
2020-05-07 00:38:14.319 +03:00 [Error] Failed executing DbCommand ("2"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""CREATE TABLE [Dockets] (
    [Id] nvarchar(450) NOT NULL,
    [Name] nvarchar(max) NULL,
    [Instance] nvarchar(max) NULL,
    CONSTRAINT [PK_Dockets] PRIMARY KEY ([Id])
);"
System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'Dockets' in the database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:8262167b-c83e-4270-a670-c4615d8b3096
Error Number:2714,State:6,Class:16
2020-05-07 00:38:39.692 +03:00 [Error] Failed executing DbCommand ("2"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""CREATE TABLE [Dockets] (
    [Id] nvarchar(450) NOT NULL,
    [Name] nvarchar(max) NULL,
    [Instance] nvarchar(max) NULL,
    CONSTRAINT [PK_Dockets] PRIMARY KEY ([Id])
);"
System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'Dockets' in the database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:b90ac2d2-9d09-4b61-acfa-34a3e760cd42
Error Number:2714,State:6,Class:16
2020-05-07 00:45:02.047 +03:00 [Error] Facility Id missing 10009
DwapiCentral.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10009
   at DwapiCentral.Cbs.Core.Service.MgsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 79
   at DwapiCentral.Cbs.Core.Service.MgsService.Process(IEnumerable`1 metricMigrationExtracts, Boolean sync) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 46
2020-05-07 00:45:02.078 +03:00 [Error] Facility Id missing 10009
DwapiCentral.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10009
   at DwapiCentral.Cbs.Core.Service.MgsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 79
   at DwapiCentral.Cbs.Core.Service.MgsService.Process(IEnumerable`1 metricMigrationExtracts, Boolean sync) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 46
2020-05-07 00:45:02.078 +03:00 [Error] Facility Id missing 10009
DwapiCentral.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10009
   at DwapiCentral.Cbs.Core.Service.MgsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 79
   at DwapiCentral.Cbs.Core.Service.MgsService.Process(IEnumerable`1 metricMigrationExtracts, Boolean sync) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 46
2020-05-07 00:45:02.079 +03:00 [Error] Facility Id missing 10009
DwapiCentral.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10009
   at DwapiCentral.Cbs.Core.Service.MgsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 79
   at DwapiCentral.Cbs.Core.Service.MgsService.Process(IEnumerable`1 metricMigrationExtracts, Boolean sync) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 46
2020-05-07 00:45:02.079 +03:00 [Error] Facility Id missing 10009
DwapiCentral.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10009
   at DwapiCentral.Cbs.Core.Service.MgsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 79
   at DwapiCentral.Cbs.Core.Service.MgsService.Process(IEnumerable`1 metricMigrationExtracts, Boolean sync) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 46
2020-05-07 00:45:02.079 +03:00 [Error] Facility Id missing 10009
DwapiCentral.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10009
   at DwapiCentral.Cbs.Core.Service.MgsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 79
   at DwapiCentral.Cbs.Core.Service.MgsService.Process(IEnumerable`1 metricMigrationExtracts, Boolean sync) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 46
2020-05-07 00:45:02.215 +03:00 [Error] The best overloaded method match for 'DwapiCentral.Cbs.Core.Exchange.StatsDto.StatsDto(int, System.DateTime, string)' has some invalid arguments
2020-05-07 01:22:25.216 +03:00 [Error] verify error
DwapiCentral.SharedKernel.Exceptions.SubscriberNotAuthorizedException: Subscriber DWAPI not authorized
   at DwapiCentral.Cbs.Core.CommandHandler.VerifySubscriberHandler.Handle(VerifySubscriber request, CancellationToken cancellationToken) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral.Cbs.Core/CommandHandler/VerifySubscriberHandler.cs:line 34
   at DwapiCentral.Controllers.MgsController.Verify(VerifySubscriber subscriber) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral/Controllers/MgsController.cs:line 39
2020-05-07 01:23:16.426 +03:00 [Error] verify error
DwapiCentral.SharedKernel.Exceptions.SubscriberNotAuthorizedException: Subscriber DWAPI not authorized
   at DwapiCentral.Cbs.Core.CommandHandler.VerifySubscriberHandler.Handle(VerifySubscriber request, CancellationToken cancellationToken) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral.Cbs.Core/CommandHandler/VerifySubscriberHandler.cs:line 34
   at DwapiCentral.Controllers.MgsController.Verify(VerifySubscriber subscriber) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral/Controllers/MgsController.cs:line 39
2020-05-07 01:26:08.064 +03:00 [Error] verify error
DwapiCentral.SharedKernel.Exceptions.SubscriberNotAuthorizedException: Subscriber DWAPI not authorized
   at DwapiCentral.Cbs.Core.CommandHandler.VerifySubscriberHandler.Handle(VerifySubscriber request, CancellationToken cancellationToken) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral.Cbs.Core/CommandHandler/VerifySubscriberHandler.cs:line 34
   at DwapiCentral.Controllers.MgsController.Verify(VerifySubscriber subscriber) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral/Controllers/MgsController.cs:line 39
2020-05-07 09:50:57.477 +03:00 [Error] verify error
DwapiCentral.SharedKernel.Exceptions.SubscriberNotAuthorizedException: Subscriber DWAPI not authorized
   at DwapiCentral.Cbs.Core.CommandHandler.VerifySubscriberHandler.Handle(VerifySubscriber request, CancellationToken cancellationToken) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral.Cbs.Core/CommandHandler/VerifySubscriberHandler.cs:line 34
   at DwapiCentral.Controllers.MgsController.Verify(VerifySubscriber subscriber) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral/Controllers/MgsController.cs:line 39
2020-05-07 09:56:47.133 +03:00 [Error] verify error
DwapiCentral.SharedKernel.Exceptions.SubscriberNotAuthorizedException: Subscriber DWAPI not authorized
   at DwapiCentral.Cbs.Core.CommandHandler.VerifySubscriberHandler.Handle(VerifySubscriber request, CancellationToken cancellationToken) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral.Cbs.Core/CommandHandler/VerifySubscriberHandler.cs:line 34
   at DwapiCentral.Controllers.MgsController.Verify(VerifySubscriber subscriber) in /Users/koskedk/Projects/hmis/dwh/dwapi/cbs/DwapiCentral/Controllers/MgsController.cs:line 39
